--
-- PostgreSQL database dump
--

-- Dumped from database version 14.1
-- Dumped by pg_dump version 14.1

-- Started on 2021-12-29 13:06:22

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 209 (class 1259 OID 24577)
-- Name: Account; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Account" (
    account_id integer NOT NULL,
    username character varying(256) NOT NULL,
    password character varying(256) NOT NULL,
    permission integer NOT NULL,
    fullname character varying(256),
    national_id character(12),
    dob date,
    state "char",
    quarantine_location_id integer,
    city character varying(256),
    district character varying(256),
    ward character varying(256)
);

--
-- TOC entry 220 (class 1259 OID 24705)
-- Name: Account_account_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Account" ALTER COLUMN account_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public."Account_account_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 24675)
-- Name: Category; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Category" (
    category_id integer NOT NULL,
    name character varying(256) NOT NULL
);

--
-- TOC entry 224 (class 1259 OID 24746)
-- Name: Category_category_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Category" ALTER COLUMN category_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public."Category_category_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- TOC entry 223 (class 1259 OID 24729)
-- Name: Log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Log" (
    log_id integer NOT NULL,
    account_id integer,
    tablename character varying(20),
    type character varying(20),
    discription character varying(256),
    create_at timestamp without time zone
);

--
-- TOC entry 224 (class 1259 OID 24746)
-- Name: Log_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Log" ALTER COLUMN log_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public."Log_log_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 24724)
-- Name: Necessary; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Necessary" (
    necessary_id integer NOT NULL,
    name character varying(256) NOT NULL,
    price integer NOT NULL,
    unit character varying(10) NOT NULL,
    category_id integer NOT NULL
);

--
-- TOC entry 213 (class 1259 OID 24632)
-- Name: Necessary_Images; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Necessary_Images" (
    necessary_id integer NOT NULL,
    img_url character varying(256) NOT NULL
);


--
-- TOC entry 212 (class 1259 OID 24627)
-- Name: Necessary_Package; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Necessary_Package" (
    package_id integer NOT NULL,
    necessary_id integer NOT NULL,
    max_necessary_per_package integer NOT NULL
);

--
-- TOC entry 221 (class 1259 OID 24723)
-- Name: Necessary_necessary_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Necessary" ALTER COLUMN necessary_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public."Necessary_necessary_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 214 (class 1259 OID 24639)
-- Name: Order; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Order" (
    order_id integer NOT NULL,
    account_id integer NOT NULL,
    create_at timestamp without time zone NOT NULL,
    total integer NOT NULL
);

--
-- TOC entry 215 (class 1259 OID 24644)
-- Name: Order_Details; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Order_Details" (
    detail_id integer NOT NULL,
    order_id integer NOT NULL,
    package_name character varying(256) NOT NULL,
    amount integer NOT NULL,
    total integer NOT NULL
);

--
-- TOC entry 227 (class 1259 OID 24759)
-- Name: Order_details_detail_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Order_Details" ALTER COLUMN detail_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Order_details_detail_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- TOC entry 226 (class 1259 OID 24754)
-- Name: Order_Order_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Order" ALTER COLUMN order_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public."Order_Order_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 211 (class 1259 OID 24620)
-- Name: Package; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Package" (
    package_id integer NOT NULL,
    name character varying(256) NOT NULL,
    period integer NOT NULL,
    max_per_person integer NOT NULL
);

--
-- TOC entry 227 (class 1259 OID 24759)
-- Name: Package_package_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Package" ALTER COLUMN package_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Package_package_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 24682)
-- Name: Payment_Account; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Payment_Account" (
    account_id integer NOT NULL,
    balance bigint NOT NULL,
    password character varying(256)
);

--
-- TOC entry 216 (class 1259 OID 24649)
-- Name: Quarantine_Location; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Quarantine_Location" (
    location_id integer NOT NULL,
    name character varying(256) NOT NULL,
    num_patients integer NOT NULL,
    capacity integer NOT NULL
);

--
-- TOC entry 228 (class 1259 OID 24768)
-- Name: Quarantine_Location_location_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Quarantine_Location" ALTER COLUMN location_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Quarantine_Location_location_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 210 (class 1259 OID 24593)
-- Name: Related_Account; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Related_Account" (
    account_id integer NOT NULL,
    related_id integer NOT NULL
);



ALTER TABLE ONLY public."Account"
    ADD CONSTRAINT "Accounts_pkey" PRIMARY KEY (account_id);


--
-- TOC entry 3235 (class 2606 OID 24681)
-- Name: Category Category_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Category"
    ADD CONSTRAINT "Category_pkey" PRIMARY KEY (category_id);


--
-- TOC entry 3243 (class 2606 OID 24733)
-- Name: Log Log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Log"
    ADD CONSTRAINT "Log_pkey" PRIMARY KEY (log_id);


--
-- TOC entry 3227 (class 2606 OID 24749)
-- Name: Necessary_Images Necessary_images_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Necessary_Images"
    ADD CONSTRAINT "Necessary_images_pkey" PRIMARY KEY (necessary_id, img_url);


--
-- TOC entry 3225 (class 2606 OID 24631)
-- Name: Necessary_Package Necessary_package_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Necessary_Package"
    ADD CONSTRAINT "Necessary_package_pkey" PRIMARY KEY (package_id, necessary_id);


--
-- TOC entry 3241 (class 2606 OID 24728)
-- Name: Necessary Necessary_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Necessary"
    ADD CONSTRAINT "Necessary_pkey" PRIMARY KEY (necessary_id);


--
-- TOC entry 3231 (class 2606 OID 24648)
-- Name: Order_Details Order details_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Order_Details"
    ADD CONSTRAINT "Order details_pkey" PRIMARY KEY (detail_id);


--
-- TOC entry 3229 (class 2606 OID 24643)
-- Name: Order Order_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Order"
    ADD CONSTRAINT "Order_pkey" PRIMARY KEY (order_id);


--
-- TOC entry 3223 (class 2606 OID 24626)
-- Name: Package Package_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Package"
    ADD CONSTRAINT "Package_pkey" PRIMARY KEY (package_id);


--
-- TOC entry 3233 (class 2606 OID 24655)
-- Name: Quarantine_Location Quarantine location_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Quarantine_Location"
    ADD CONSTRAINT "Quarantine location_pkey" PRIMARY KEY (location_id);


--
-- TOC entry 3221 (class 2606 OID 24669)
-- Name: Related_Account Related Account_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Related_Account"
    ADD CONSTRAINT "Related Account_pkey" PRIMARY KEY (account_id, related_id);



--
-- TOC entry 3245 (class 2606 OID 24596)
-- Name: Related_Account fk_AccountRelate_Account; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Related_Account"
    ADD CONSTRAINT "fk_AccountRelate_Account" FOREIGN KEY (account_id) REFERENCES public."Account"(account_id);


--
-- TOC entry 3244 (class 2606 OID 24663)
-- Name: Account fk_Account_Quarantinelocation; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Account"
    ADD CONSTRAINT "fk_Account_Quarantinelocation" FOREIGN KEY (quarantine_location_id) REFERENCES public."Quarantine_Location"(location_id) NOT VALID;


--
-- TOC entry 3254 (class 2606 OID 24774)
-- Name: Log fk_Log_Account; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Log"
    ADD CONSTRAINT "fk_Log_Account" FOREIGN KEY (log_id) REFERENCES public."Account"(account_id) NOT VALID;


--
-- TOC entry 3247 (class 2606 OID 24794)
-- Name: Necessary_Package fk_NeccesaryPackage_Necessary; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Necessary_Package"
    ADD CONSTRAINT "fk_NeccesaryPackage_Necessary" FOREIGN KEY (necessary_id) REFERENCES public."Necessary"(necessary_id) NOT VALID;


--
-- TOC entry 3248 (class 2606 OID 24799)
-- Name: Necessary_Package fk_NeccesaryPackage_Package; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Necessary_Package"
    ADD CONSTRAINT "fk_NeccesaryPackage_Package" FOREIGN KEY (package_id) REFERENCES public."Package"(package_id) NOT VALID;


--
-- TOC entry 3249 (class 2606 OID 24789)
-- Name: Necessary_Images fk_NecessaryImage_Necessary; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Necessary_Images"
    ADD CONSTRAINT "fk_NecessaryImage_Necessary" FOREIGN KEY (necessary_id) REFERENCES public."Necessary"(necessary_id) NOT VALID;


--
-- TOC entry 3253 (class 2606 OID 24784)
-- Name: Necessary fk_Necessary_Category; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Necessary"
    ADD CONSTRAINT "fk_Necessary_Category" FOREIGN KEY (category_id) REFERENCES public."Category"(category_id) NOT VALID;


--
-- TOC entry 3251 (class 2606 OID 24804)
-- Name: Order_Details fk_OrderDetail_Order; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Order_Details"
    ADD CONSTRAINT "fk_OrderDetail_Order" FOREIGN KEY (order_id) REFERENCES public."Order"(order_id) NOT VALID;


--
-- TOC entry 3250 (class 2606 OID 24779)
-- Name: Order fk_Order_Account; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Order"
    ADD CONSTRAINT "fk_Order_Account" FOREIGN KEY (account_id) REFERENCES public."Account"(account_id) NOT VALID;


--
-- TOC entry 3246 (class 2606 OID 24601)
-- Name: Related_Account fk_RelatedAccount_Account; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Related_Account"
    ADD CONSTRAINT "fk_RelatedAccount_Account" FOREIGN KEY (related_id) REFERENCES public."Account"(account_id) NOT VALID;


-- Completed on 2021-12-29 13:06:22

--
-- PostgreSQL database dump complete
--

